# Generated by Django 5.2.7 on 2026-01-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditreportquery',
            new_name='api_creditr_provide_5328af_idx',
            old_name='api_creditr_provider_f470ce_idx',
        ),
    ]
