# Generated by Django 5.2.7 on 2026-01-31 15:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_api_creditr_provider_f470ce_idx_api_creditr_provide_5328af_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditreportquery',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.credit_report_upload_to),
        ),
    ]
