# Generated by Django 5.1.4 on 2025-12-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='consulted_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='consulted_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='forwarded_for',
            field=models.TextField(blank=True, help_text='Cabecera X-Forwarded-For completa'),
        ),
    ]
