# Generated by Django 5.1.4 on 2025-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_accesslog_consulted_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='real_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Cabecera X-Real-IP si llega', null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, help_text='IP de entrada al contenedor', null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='response_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
