# Generated by Django 5.1.4 on 2025-12-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_accesslog_real_ip_accesslog_remote_addr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='real_ip',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='remote_addr',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='response_full_name',
        ),
    ]
