# Generated by Django 5.2.7 on 2026-01-30 16:33

import uuid
from django.db import migrations, models


def populate_public_id(apps, schema_editor):
    ConsentOTP = apps.get_model("integrations", "ConsentOTP")
    for row in ConsentOTP.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_consentotp_pdf_and_decision_fields'),
    ]

    operations = [
        migrations.RunPython(populate_public_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='consentotp',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
