# Generated by Django 5.2.7 on 2026-01-31

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_alter_consentotp_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreselectaQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("id_number", models.CharField(max_length=50)),
                ("id_type", models.CharField(max_length=10)),
                ("first_last_name", models.CharField(blank=True, max_length=200)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("request_payload", models.JSONField()),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=50)),
                ("risk_level", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("forwarded_for", models.TextField(blank=True, help_text="Cabecera X-Forwarded-For completa")),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="consentotp",
            name="preselecta_query",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consents",
                to="integrations.preselectaquery",
            ),
        ),
    ]
