# Generated by Django 5.2.7 on 2026-01-31 15:59

import integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_preselectaquery_and_consentotp_preselecta_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentotp',
            name='consent_pdf',
            field=models.FileField(blank=True, null=True, upload_to=integrations.models.consent_upload_to),
        ),
    ]
