# Generated by Django 5.2.7 on 2026-02-20 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_otp_contingency_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='destination_full_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='otp_code_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='sms_message_sid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='transaction_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='validation_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='validation_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='provider',
            field=models.CharField(choices=[('twilio_messaging', 'Twilio Messaging'), ('twilio_verify', 'Twilio Verify (legacy)'), ('internal_email', 'Internal Email OTP')], max_length=30),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('blocked', 'Blocked'), ('failed_send', 'Failed Send')], default='pending', max_length=20),
        ),
    ]
